# Generated by Django 5.0.6 on 2024-07-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_publication_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffee',
            options={'verbose_name': 'Кофе', 'verbose_name_plural': 'Кофе'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
