# Generated by Django 5.0.6 on 2024-07-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='avatar',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
