# Generated by Django 5.0.6 on 2024-07-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_feedback_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MokkoContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=100)),
                ('email', models.EmailField(max_length=155)),
            ],
            options={
                'verbose_name': 'Контакты Мокко',
                'verbose_name_plural': 'Контакты Мокко',
            },
        ),
    ]
