# Generated by Django 5.0.6 on 2024-07-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_mokkocontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mokkocontact',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
